// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2Sport_BE.Repository.Data;

#nullable disable

namespace _2Sport_BE.Migrations
{
    [DbContext(typeof(TwoSportCapstoneDbContext))]
    [Migration("20241227093041_addPayDateToOrder")]
    partial class addPayDateToOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("Content");

                    b.Property<string>("CoverImgPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasColumnName("CoverImgPath");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedStaffId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedStaffId");

                    b.Property<int?>("EditedByStaffId")
                        .HasColumnType("int")
                        .HasColumnName("EditedByStaffId");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("SubTitle");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedStaffId");

                    b.HasIndex("EditedByStaffId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Bookmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("BranchName");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hotline")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar")
                        .HasColumnName("Hotline");

                    b.Property<string>("ImgAvatarPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasColumnName("ImgAvatarPath");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Location");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("BrandName");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasColumnName("Logo");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.CartItem", b =>
                {
                    b.Property<Guid>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryImgPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("CategoryImgPath");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("CategoryName");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("SportId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("ProductCode");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LoyaltyPoints")
                        .HasColumnType("int")
                        .HasColumnName("LoyaltyPoints");

                    b.Property<string>("MembershipLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("MembershipLevel");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerException")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FullName");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("PhoneNumber");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.ImagesVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasColumnName("ImageUrl");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasColumnName("VideoUrl");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ImagesVideos");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.ImportHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Action");

                    b.Property<string>("Color")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Color");

                    b.Property<int?>("Condition")
                        .HasColumnType("int")
                        .HasColumnName("Condition");

                    b.Property<DateTime?>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("ManagerId");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("ProductCode");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("ProductName");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("RentPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("RentPrice");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Size");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StaffId");

                    b.ToTable("ImportHistories");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("ProductCode");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchId");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartDate");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("UserId");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("IsRead");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Message");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ReadAt");

                    b.Property<string>("ReferenceLink")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ReferenceLink");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Type");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchId");

                    b.Property<string>("BranchName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BranchName");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Color");

                    b.Property<int?>("Condition")
                        .HasColumnType("int")
                        .HasColumnName("Condition");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("ImgAvatarPath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasColumnName("ImgAvatarPath");

                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProductCode");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProductName");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.Property<string>("SaleOrderCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("SaleOrderCode");

                    b.Property<int?>("SaleOrderId")
                        .HasColumnType("int")
                        .HasColumnName("SaleOrderId");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Size");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal")
                        .HasColumnName("UnitPrice");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("SaleOrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PaymentMethodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("PaymentMethodName");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int")
                        .HasColumnName("BrandId");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryId");

                    b.Property<string>("Color")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Color");

                    b.Property<int?>("Condition")
                        .HasColumnType("int")
                        .HasColumnName("Condition");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("Description");

                    b.Property<int>("Discount")
                        .HasColumnType("int")
                        .HasColumnName("Discount");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Height");

                    b.Property<string>("ImgAvatarPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasColumnName("ImgAvatarPath");

                    b.Property<bool>("IsRent")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Length");

                    b.Property<string>("Offers")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("Offers");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal")
                        .HasColumnName("Price");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("ProductCode");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("ProductName");

                    b.Property<decimal?>("RentPrice")
                        .HasColumnType("decimal")
                        .HasColumnName("RentPrice");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Size");

                    b.Property<int>("SportId")
                        .HasColumnType("int")
                        .HasColumnName("SportId");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Weight");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Width");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SportId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("JwtId");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("Token");

                    b.Property<bool?>("Used")
                        .HasColumnType("bit");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.RefundRequest", b =>
                {
                    b.Property<int>("RefundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefundID"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAgreementAccepted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PaymentGatewayTransactionID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ProcessedBy")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("RefundMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RentalOrderCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RentalOrderID")
                        .HasColumnType("int");

                    b.Property<string>("SaleOrderCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SaleOrderID")
                        .HasColumnType("int");

                    b.Property<string>("StaffName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RefundID");

                    b.HasIndex("RentalOrderID");

                    b.HasIndex("SaleOrderID");

                    b.ToTable("RefundRequests");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.RentalOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Address");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchId");

                    b.Property<string>("BranchName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BranchName");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Color");

                    b.Property<int?>("Condition")
                        .HasColumnType("int")
                        .HasColumnName("Condition");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContactPhone");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<decimal?>("DamageFee")
                        .HasColumnType("decimal")
                        .HasColumnName("DamageFee");

                    b.Property<DateTime?>("DateOfReceipt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateOfReceipt");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DeliveryMethod");

                    b.Property<decimal?>("DepositAmount")
                        .HasColumnType("decimal")
                        .HasColumnName("DepositAmount");

                    b.Property<DateTime?>("DepositDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepositStatus")
                        .HasColumnType("int")
                        .HasColumnName("DepositStatus");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<DateTime?>("ExtendedDueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExtendedDueDate");

                    b.Property<decimal?>("ExtensionCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ExtensionCost");

                    b.Property<int?>("ExtensionDays")
                        .HasColumnType("int")
                        .HasColumnName("ExtensionDays");

                    b.Property<int?>("ExtensionStatus")
                        .HasColumnType("int")
                        .HasColumnName("ExtensionStatus");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FullName");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Gender");

                    b.Property<string>("ImgAvatarPath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasColumnName("ImgAvatarPath");

                    b.Property<bool?>("IsExtended")
                        .HasColumnType("bit")
                        .HasColumnName("IsExtended");

                    b.Property<bool?>("IsInspected")
                        .HasColumnType("bit")
                        .HasColumnName("IsInspected");

                    b.Property<bool?>("IsRestocked")
                        .HasColumnType("bit")
                        .HasColumnName("IsRestocked");

                    b.Property<decimal?>("LateFee")
                        .HasColumnType("decimal")
                        .HasColumnName("LateFee");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Note");

                    b.Property<string>("OrderImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("OrderImage");

                    b.Property<int?>("OrderStatus")
                        .HasColumnType("int")
                        .HasColumnName("OrderStatus");

                    b.Property<string>("ParentOrderCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("ParentOrderCode");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PaymentDate");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("int")
                        .HasColumnName("PaymentMethodId");

                    b.Property<int?>("PaymentStatus")
                        .HasColumnType("int")
                        .HasColumnName("PaymentStatus");

                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProductCode");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProductName");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Reason");

                    b.Property<decimal?>("RentPrice")
                        .HasColumnType("decimal")
                        .HasColumnName("RentPrice");

                    b.Property<int>("RentalDays")
                        .HasColumnType("int")
                        .HasColumnName("RentalDays");

                    b.Property<DateTime?>("RentalEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RentalOrderCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("RentalOrderCode");

                    b.Property<DateTime?>("RentalStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ShipmentDetailId")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Size");

                    b.Property<decimal?>("SubTotal")
                        .HasColumnType("decimal")
                        .HasColumnName("SubTotal");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal")
                        .HasColumnName("TotalAmount");

                    b.Property<decimal?>("TranSportFee")
                        .HasColumnType("decimal")
                        .HasColumnName("TranSportFee");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("TransactionId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("ShipmentDetailId");

                    b.HasIndex("UserId");

                    b.ToTable("RentalOrders");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("ProductCode");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ReviewContent");

                    b.Property<int?>("SaleOrderId")
                        .HasColumnType("int")
                        .HasColumnName("SaleOrderId");

                    b.Property<decimal?>("Star")
                        .HasColumnType("decimal")
                        .HasColumnName("Star");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleOrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("RoleName");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.SaleOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SaleOrderId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Address");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchId");

                    b.Property<string>("BranchName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BranchName");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContactPhone");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DateOfReceipt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateOfReceipt");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DeliveryMethod");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FullName");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Gender");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Note");

                    b.Property<string>("OrderImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("OrderImage");

                    b.Property<int?>("OrderStatus")
                        .HasColumnType("int")
                        .HasColumnName("OrderStatus");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PaymentDate");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("int")
                        .HasColumnName("PaymentMethodId");

                    b.Property<int?>("PaymentStatus")
                        .HasColumnType("int")
                        .HasColumnName("PaymentStatus");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Reason");

                    b.Property<string>("SaleOrderCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("SaleOrderCode");

                    b.Property<int?>("ShipmentDetailId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SubTotal")
                        .HasColumnType("decimal")
                        .HasColumnName("SubTotal");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal")
                        .HasColumnName("TotalAmount");

                    b.Property<decimal?>("TranSportFee")
                        .HasColumnType("decimal")
                        .HasColumnName("TranSportFee");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("TransactionId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("ShipmentDetailId");

                    b.HasIndex("UserId");

                    b.ToTable("SaleOrders");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.ShipmentDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Address");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("FullName");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar")
                        .HasColumnName("PhoneNumber");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ShipmentDetails");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Name");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Sports");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchId");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("ManagerId");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Position");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartDate");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("StaffId");

                    b.HasIndex("BranchId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("UserId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.TwilioAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountSId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("AccountSId");

                    b.Property<string>("AuthToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("AuthToken");

                    b.Property<string>("FromNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar")
                        .HasColumnName("FromNumber");

                    b.Property<string>("ToNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar")
                        .HasColumnName("ToNumber");

                    b.HasKey("Id");

                    b.ToTable("TwilioAccounts");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("IsEmailConfirmed");

                    b.Property<string>("FacebookId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FullName");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Gender");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashPassword")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HashPassword");

                    b.Property<string>("ImgAvatarPath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasColumnName("ImgAvatarPath");

                    b.Property<bool?>("IsActived")
                        .HasColumnType("bit")
                        .HasColumnName("IsActived");

                    b.Property<int>("OTP")
                        .HasColumnType("int")
                        .HasColumnName("OTP");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("IsPhoneNumberConfirmed");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchId");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    b.Property<int?>("TotalQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ProductId");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Blog", b =>
                {
                    b.HasOne("_2Sport_BE.Repository.Models.Staff", "CreatedByStaff")
                        .WithMany("CreatedBlogs")
                        .HasForeignKey("CreatedStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_2Sport_BE.Repository.Models.Staff", "EditedByStaff")
                        .WithMany("EditedBlogs")
                        .HasForeignKey("EditedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByStaff");

                    b.Navigation("EditedByStaff");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Bookmark", b =>
                {
                    b.HasOne("_2Sport_BE.Repository.Models.Blog", "Blog")
                        .WithMany("Bookmarks")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2Sport_BE.Repository.Models.User", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.CartItem", b =>
                {
                    b.HasOne("_2Sport_BE.Repository.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("_2Sport_BE.Repository.Models.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Category", b =>
                {
                    b.HasOne("_2Sport_BE.Repository.Models.Sport", "Sport")
                        .WithMany("Categories")
                        .HasForeignKey("SportId");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Comment", b =>
                {
                    b.HasOne("_2Sport_BE.Repository.Models.Comment", "ParentComment")
                        .WithMany()
                        .HasForeignKey("ParentCommentId");

                    b.HasOne("_2Sport_BE.Repository.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Customer", b =>
                {
                    b.HasOne("_2Sport_BE.Repository.Models.User", "User")
                        .WithMany("Customers")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Feedback", b =>
                {
                    b.HasOne("_2Sport_BE.Repository.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.ImagesVideo", b =>
                {
                    b.HasOne("_2Sport_BE.Repository.Models.Product", "Product")
                        .WithMany("ImagesVideos")
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.ImportHistory", b =>
                {
                    b.HasOne("_2Sport_BE.Repository.Models.Manager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2Sport_BE.Repository.Models.Product", "Product")
                        .WithMany("ImportHistories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2Sport_BE.Repository.Models.Staff", null)
                        .WithMany("ImportHistories")
                        .HasForeignKey("StaffId");

                    b.Navigation("Manager");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Like", b =>
                {
                    b.HasOne("_2Sport_BE.Repository.Models.Product", null)
                        .WithMany("Likes")
                        .HasForeignKey("ProductId");

                    b.HasOne("_2Sport_BE.Repository.Models.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Manager", b =>
                {
                    b.HasOne("_2Sport_BE.Repository.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.HasOne("_2Sport_BE.Repository.Models.User", "User")
                        .WithMany("Managers")
                        .HasForeignKey("UserId");

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Notification", b =>
                {
                    b.HasOne("_2Sport_BE.Repository.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.OrderDetail", b =>
                {
                    b.HasOne("_2Sport_BE.Repository.Models.SaleOrder", "SaleOrder")
                        .WithMany("OrderDetails")
                        .HasForeignKey("SaleOrderId");

                    b.Navigation("SaleOrder");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Product", b =>
                {
                    b.HasOne("_2Sport_BE.Repository.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2Sport_BE.Repository.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2Sport_BE.Repository.Models.Sport", "Sport")
                        .WithMany("Products")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.RefreshToken", b =>
                {
                    b.HasOne("_2Sport_BE.Repository.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.RefundRequest", b =>
                {
                    b.HasOne("_2Sport_BE.Repository.Models.RentalOrder", "RentalOrder")
                        .WithMany("RefundRequests")
                        .HasForeignKey("RentalOrderID");

                    b.HasOne("_2Sport_BE.Repository.Models.SaleOrder", "SaleOrder")
                        .WithMany("RefundRequests")
                        .HasForeignKey("SaleOrderID");

                    b.Navigation("RentalOrder");

                    b.Navigation("SaleOrder");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.RentalOrder", b =>
                {
                    b.HasOne("_2Sport_BE.Repository.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.HasOne("_2Sport_BE.Repository.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("RentalOrders")
                        .HasForeignKey("PaymentMethodId");

                    b.HasOne("_2Sport_BE.Repository.Models.ShipmentDetail", null)
                        .WithMany("RentalOrders")
                        .HasForeignKey("ShipmentDetailId");

                    b.HasOne("_2Sport_BE.Repository.Models.User", "User")
                        .WithMany("RentalOrders")
                        .HasForeignKey("UserId");

                    b.Navigation("Branch");

                    b.Navigation("PaymentMethod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Review", b =>
                {
                    b.HasOne("_2Sport_BE.Repository.Models.Product", null)
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId");

                    b.HasOne("_2Sport_BE.Repository.Models.SaleOrder", "SaleOrder")
                        .WithMany("Reviews")
                        .HasForeignKey("SaleOrderId");

                    b.HasOne("_2Sport_BE.Repository.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId");

                    b.Navigation("SaleOrder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.SaleOrder", b =>
                {
                    b.HasOne("_2Sport_BE.Repository.Models.Branch", "Branch")
                        .WithMany("Orders")
                        .HasForeignKey("BranchId");

                    b.HasOne("_2Sport_BE.Repository.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("SaleOrders")
                        .HasForeignKey("PaymentMethodId");

                    b.HasOne("_2Sport_BE.Repository.Models.ShipmentDetail", null)
                        .WithMany("SaleOrders")
                        .HasForeignKey("ShipmentDetailId");

                    b.HasOne("_2Sport_BE.Repository.Models.User", "User")
                        .WithMany("SaleOrders")
                        .HasForeignKey("UserId");

                    b.Navigation("Branch");

                    b.Navigation("PaymentMethod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.ShipmentDetail", b =>
                {
                    b.HasOne("_2Sport_BE.Repository.Models.User", "User")
                        .WithMany("ShipmentDetails")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Staff", b =>
                {
                    b.HasOne("_2Sport_BE.Repository.Models.Branch", "Branch")
                        .WithMany("EmployeeDetails")
                        .HasForeignKey("BranchId");

                    b.HasOne("_2Sport_BE.Repository.Models.Manager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.HasOne("_2Sport_BE.Repository.Models.User", "User")
                        .WithMany("Staffs")
                        .HasForeignKey("UserId");

                    b.Navigation("Branch");

                    b.Navigation("Manager");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.User", b =>
                {
                    b.HasOne("_2Sport_BE.Repository.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Warehouse", b =>
                {
                    b.HasOne("_2Sport_BE.Repository.Models.Branch", "Branch")
                        .WithMany("Warehouses")
                        .HasForeignKey("BranchId");

                    b.HasOne("_2Sport_BE.Repository.Models.Product", "Product")
                        .WithMany("Warehouses")
                        .HasForeignKey("ProductId");

                    b.Navigation("Branch");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Blog", b =>
                {
                    b.Navigation("Bookmarks");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Branch", b =>
                {
                    b.Navigation("EmployeeDetails");

                    b.Navigation("Orders");

                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.PaymentMethod", b =>
                {
                    b.Navigation("RentalOrders");

                    b.Navigation("SaleOrders");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Product", b =>
                {
                    b.Navigation("ImagesVideos");

                    b.Navigation("ImportHistories");

                    b.Navigation("Likes");

                    b.Navigation("Reviews");

                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.RentalOrder", b =>
                {
                    b.Navigation("RefundRequests");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.SaleOrder", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("RefundRequests");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.ShipmentDetail", b =>
                {
                    b.Navigation("RentalOrders");

                    b.Navigation("SaleOrders");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Sport", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.Staff", b =>
                {
                    b.Navigation("CreatedBlogs");

                    b.Navigation("EditedBlogs");

                    b.Navigation("ImportHistories");
                });

            modelBuilder.Entity("_2Sport_BE.Repository.Models.User", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("CartItems");

                    b.Navigation("Customers");

                    b.Navigation("Likes");

                    b.Navigation("Managers");

                    b.Navigation("RefreshTokens");

                    b.Navigation("RentalOrders");

                    b.Navigation("Reviews");

                    b.Navigation("SaleOrders");

                    b.Navigation("ShipmentDetails");

                    b.Navigation("Staffs");
                });
#pragma warning restore 612, 618
        }
    }
}
